START:	            equ $0000	;	START - Cold start routine
ERROR_1:            equ $0008	;	ERROR
PRINT_A_1:      	equ $0010	;	PRINT A CHARACTER - Print character in "A"
GET_CHAR:	        equ $0018	;	COLLECT CHARACTER - 
                                ;      The contents of the location currently addressed by CH-ADD are 
                                ;      fetched. A return is made if the value represents a printable 
                                ;      character, otherwise CH-ADD is incremented and the tests repeated.
NEXT_CHAR:      	equ $0020	;	COLLECT NEXT CHARACTER' RESTART - 
                                ;       As a BASIC line is interpreted, this routine is called repeatedly to step along the line.
FP_CALC:	        equ $0028	;	CALCULATOR' RESTART
BC_SPACES:	        equ $0030	;	MAKE BC SPACES' RESTART
MASK_INT:       	equ $0038	;	MASKABLE INTERRUPT' ROUTINE
ERROR_2:	        equ $0053	;	ERROR-2' ROUTINE
CHCH_ADD_1:	        equ $0074	;	CH-ADD+1' SUBROUTINE
SKIP_OVER:	        equ $007D	;	SKIP-OVER' SUBROUTINE
KEY_SCAN:       	equ $028E	;	KEYBOARD SCANNING' SUBROUTINE
KEYBOARD:	        equ $02BF	;	KEYBOARD' SUBROUTINE
K-TEST:	            equ $031E	;	K-TEST' SUBROUTINE
KEYBOARD DECODING:	equ $0333	;	KEYBOARD DECODING' SUBROUTINE
BEEPER:	            equ $03B5	;	BEEPER' SUBROUTINE
BEEP:       	    equ $03F8	;	BEEP' COMMAND ROUTINE
SA_BYTES:	        equ $04C2	;	SA-BYTES' SUBROUTINE
SA_LD_RET:	        equ $053F	;	SA/LD-RET' SUBROUTINE
LD_BYTES:	        equ $0556	;	LD-BYTES' SUBROUTINE
LD_EDGE_2:        	equ $05E3	;	LD-EDGE-2' AND 'LD-EDGE-1' SUBROUTINES 
LD_EDGE_1:        	equ $05E7	;	LD-EDGE-2' AND 'LD-EDGE-1' SUBROUTINES 
SAVE_ECT:       	equ $0605	;	SAVE, LOAD, VERIFY and MERGE' COMMAND ROUTINES
VR_CONTRL:	        equ $07CB	;	VERIFY' CONTROL ROUTINE
LD_BLOCK:       	equ $0802	;	LOAD A DATA BLOCK' SUBROUTINE
LD_CONTRL:	        equ $0808	;	LOAD' CONTROL ROUTINE
ME_CONTRL:	        equ $08B6	;	MERGE' CONTROL ROUTINE
ME_ENTER:	        equ $092C	;	MERGE A LINE OR A VARIABLE' SUBROUTINE
SA_CONTRL:	        equ $0970	;	SAVE' CONTROL ROUTINE
PRINT_OUT:	        equ $09F4	;	PRINT-OUT' ROUTINES
PO_BACK_1:      	equ $0A23	;	CURSOR LEFT' SUBROUTINE
PO_RIGHT:	        equ $0A3D	;	CURSOR RIGHT' SUBROUTINE
PO_ENTER:	        equ $0A4F	;	CARRIAGE RETURN' SUBROUTINE
PO_COMMA:	        equ $0A5F	;	PRINT COMMA' SUBROUTINE
PO_QUEST:	        equ $0A69	;	PRINT A QUESTION MARK' SUBROUTINE
PO_TV_2:	        equ $0A6D	;	CONTROL CHARACTERS WITH OPERANDS' ROUTINE
PO_ABLE:	        equ $0AD9	;	PRINTABLE CHARACTER CODES
PO_STORE:	        equ $0ADC	;	POSITION STORE' SUBROUTINE
PO_FETCH:	        equ $0B03	;	POSITION FETCH' SUBROUTINE
PO_ANY:     	    equ $0B24	;	PRINT ANY CHARACTER(S)' SUBROUTINE
PO_ATTR:	        equ $0BDB	;	SET ATTRIBUTE BYTE' SUBROUTINE
PO_MSG:         	equ $0C0A	;	MESSAGE PRINTING' SUBROUTINE
PO_SAVE:	        equ $0C3B	;	PO-SAVE' SUBROUTINE
PO_SEARCH:	        equ $0C41	;	TABLE SEARCH' SUBROUTINE
PO_SCR:         	equ $0C55	;	TEST FOR SCROLL' SUBROUTINE
TEMPS:          	equ $0D4D	;	TEMPORARY COLOUR ITEMS' SUBROUTINE
CLS_LOWER:      	equ $0D6B	;	CLS' COMMAND ROUTINE
CL_ALL:	            equ $0DAF	;	CLEARING THE WHOLE DISPLAY AREA' SUBROUTINE
CL_SET:         	equ $0DD9	;	CL-SET' SUBROUTINE
CL_SC_ALL:	        equ $0DFE	;	SCROLLING' SUBROUTINE
CL_LINE:	        equ $0E44	;	CLEAR LINES' SUBROUTINE
CL_ATTR:	        equ $0E88	;	CL-ATTR' SUBROUTINE
CL_ADDR:	        equ $0E9B	;	CL-ADDR' SUBROUTINE
COPY:	            equ $0EAC	;	COPY' COMMAND ROUTINE
COPY_BUFF:      	equ $0ECD	;	COPY-BUFF' SUBROUTINE
CLEAR_PRB:	        equ $0EDF	;	CLEAR PRINTER BUFFER' SUBROUTINE
COPY_LINE:	        equ $0EF4	;	COPY-LINE' SUBROUTINE
EDITOR:	            equ $0F2C	;	EDITOR' ROUTINES
ED_EDIT:    	    equ $0FA9	;	EDIT KEY' SUBROUTINE
ED_DOWN:	        equ $0FF3	;	CURSOR DOWN EDITING' SUBROUTINE
ED_LEFT:	        equ $1007	;	CURSOR LEFT EDITING' SUBROUTINE
ED_RIGHT:	        equ $100C	;	CURSOR RIGHT EDITING' SUBROUTINE
ED_DELETE:      	equ $1015	;	DELETE EDITING' SUBROUTINE
ED_IGNORE:  	    equ $101E	;	ED-IGNORE' SUBROUTINE
ED_ENTER:	        equ $1024	;	ENTER EDITING' SUBROUTINE
ED_EDGE:	        equ $1031	;	ED-EDGE' SUBROUTINE
ED_UP:	            equ $1059	;	CURSOR UP EDITING' SUBROUTINE
ED_SYMBOL:	        equ $1076	;	ED-SYMBOL' SUBROUTINE
ED_ERROR:	        equ $107F	;	ED-ERROR' SUBROUTINE
CLEAR_SP:	        equ $1097	;	CLEAR-SP' SUBROUTINE
KEY_INPUT:	        equ $10A8	;	KEYBOARD INPUT' SUBROUTINE
ED_COPY:	        equ $111D	;	LOWER SCREEN COPYING' SUBROUTINE
SET_HL:             equ $1190	;	SET-HL' AND 'SET-DE' SUBROUTINES
SET_DE:             equ $1195	;	SET-HL' AND 'SET-DE' SUBROUTINES
REMOVE_FP:      	equ $11A7	;	REMOVE-FP' SUBROUTINE
NEW:	            equ $11B7	;	NEW' COMMAND ROUTINE
MAIN_EXEC:	        equ $12A2	;	MAIN EXECUTION' LOOP
REPORT_G:	        equ $1555	;	Report G - No room for line
MAIN_ADD:	        equ $155D	;	MAIN-ADD' SUBROUTINE
REPORT_J:	        equ $15C4	;	Report J - Invalid I/O device
WAIT_KEY:	        equ $15D4	;	WAIT-KEY' SUBROUTINE
INPUT_AD:	        equ $15E6	;	INPUT-AD' SUBROUTINE
OUT_CODE:	        equ $15EF	;	MAIN PRINTING' SUBROUTINE
CHAN_OPEN:	        equ $1601	;	CHAN-OPEN' SUBROUTINE
CHAN_FLAG:	        equ $1615	;	CHAN-FLAG' SUBROUTINE
CHAN_K:	            equ $1634	;	CHANNEL 'K' FLAG' SUBROUTINE
CHAN_S:	            equ $1642	;	CHANNEL 'S' FLAG' SUBROUTINE
CHAN_P:	            equ $164D	;	CHANNEL 'P' FLAG' SUBROUTINE
ONE_SPACE:          equ $1652	;   Allocate one byte only.
MAKE_ROOM:	        equ $1655	;	MAKE-ROOM' SUBROUTINE
POINTERS:	        equ $1664	;	POINTERS' SUBROUTINE
LINE_NO_A:	        equ $1691	;	Use line number 0
LINE_NO:	        equ $1695	;	COLLECT A LINE NUMBER' SUBROUTINE
RESERVE:	        equ $169E	;	RESERVE' SUBROUTINE
SET_MIN:	        equ $16B0	;	SET-MIN' SUBROUTINE
INDEXER_1:          equ $16DB	;	Move on to the next part of the entry
INDEXER:	        equ $16DC	;	INDEXER' SUBROUTINE
CLOSE:          	equ $16E5	;	CLOSE #' COMMAND ROUTINE
CLOSE_2:        	equ $1701	;	CLOSE-2' SUBROUTINE
CLOSE_STR:	        equ $171C	;	CLOSE STREAM' SUBROUTINE
STR_DATA:	        equ $171E	;	STREAM DATA' SUBROUTINE
OPEN:           	equ $1736	;	OPEN #' COMMAND ROUTINE
OPEN_2:         	equ $175D	;	OPEN-2' SUBROUTINE
OPEN_K:	            equ $1781	;	OPEN-K' SUBROUTINE
OPEN_S:	            equ $1785	;	OPEN-S' SUBROUTINE
OPEN_P:	            equ $1789	;	OPEN-P' SUBROUTINE
CAT_ETC: 	        equ $1793	;	CAT, ERASE, FORMAT and MOVE' COMMAND ROUTINES
AUTO_LIST: 	        equ $1795	;	LIST and LLIST' COMMAND ROUTINES
LLIST:          	equ $17F5	;	LLIST' ENTRY POINT
LIST:	            equ $17F9	;	LIST' ENTRY POINT
OUT_LINE:	        equ $1855	;	PRINT A WHOLE BASIC LINE' SUBROUTINE
NUMBER:	            equ $18B6	;	NUMBER' SUBROUTINE
OUT_FLASH:      	equ $18C1	;	PRINT A FLASHING CHARACTER' SUBROUTINE
OUT_CURS:	        equ $18E1	;	PRINT THE CURSOR' SUBROUTINE
LN_FETCH:       	equ $190F	;	LN-FETCH' SUBROUTINE
OUT_SP_2:	        equ $1925	;	PRINTING CHARACTERS IN A BASIC LINE' SUBROUTINE
LINE_ADDR:      	equ $196E	;	LINE-ADDR' SUBROUTINE
CP_LINES:	        equ $1980	;	COMPARE LINE NUMBERS' SUBROUTINE
EACH_STMT:	        equ $198B	;	FIND EACH STATEMENT' SUBROUTINE
NEXT_ONE:	        equ $19B8	;	NEXT-ONE' SUBROUTINE
DIFFER:	            equ $19DD	;	DIFFERENCE' SUBROUTINE
RECLAIM_1:	        equ $19E5	;	RECLAIMING' SUBROUTINE
E_LINE_NO:	        equ $19FB	;	E-LINE-NO' SUBROUTINE
OUT_NUM_1:	        equ $1A1B	;	REPORT AND LINE NUMBER PRINTING' SUBROUTINE
LINE_SCAN:	        equ $1B17	;	MAIN PARSER' OF THE BASIC INTERPRETER
STMT_LOOP:	        equ $1B28	;	THE STATEMENT LOOP
SEPARATOR:	        equ $1B6F	;	SEPARATOR' SUBROUTINE
STMT_RET:	        equ $1B76	;	STMT-RET' SUBROUTINE
LINE_RUN:	        equ $1B8A	;	LINE-RUN' ENTRY POINT
LINE_NEW:	        equ $1B9E	;	LINE-NEW' SUBROUTINE
REM:	            equ $1BB2	;	REM' COMMAND ROUTINE

LINE-END:	equ $1BB3	;	LINE-END' ROUTINE
LINE-USE:	equ $1BBF	;	LINE-USE' ROUTINE
NEXT-LINE:	equ $1BD1	;	NEXT-LINE' ROUTINE
CHECK-END:	equ $1BEE	;	CHECK-END' SUBROUTINE
STMT-NEXT:	equ $1BF4	;	STMT-NEXT' ROUTINE
COMMAND CLASSES - +00, +03 and +05:	equ $1C0D	;	COMMAND CLASSES - +00, +03 and +05'
COMMAND CLASS +01:	equ $1C1F	;	COMMAND CLASS +01' ROUTINE
VARIABLE IN ASSIGNMENT:	equ $1C22	;	VARIABLE IN ASSIGNMENT' SUBROUTINE
COMMAND CLASS +02:	equ $1C4E	;	COMMAND CLASS +02' ROUTINE
FETCH A VALUE:	equ $1C56	;	FETCH A VALUE' SUBROUTINE
COMMAND CLASS +04:	equ $1C6C	;	COMMAND CLASS +04' ROUTINE
EXPECT NUMERIC/STRING EXPRESSIONS:	equ $1C79	;	EXPECT NUMERIC/STRING EXPRESSIONS' SUBROUTINE
SET PERMANENT COLOURS:	equ $1C96	;	SET PERMANENT COLOURS' SUBROUTINE
COMMAND CLASS +09:	equ $1CBE	;	COMMAND CLASS +09' ROUTINE
COMMAND CLASS +0B:	equ $1CDB	;	COMMAND CLASS +0B' ROUTINE
FETCH A NUMBER:	equ $1CDE	;	FETCH A NUMBER' SUBROUTINE
STOP' COMMAND ROUTINE	:	equ $1CEE	;	STOP' COMMAND ROUTINE
IF' COMMAND ROUTINE	:	equ $1CF0	;	IF' COMMAND ROUTINE
FOR' COMMAND ROUTINE	:	equ $1D03	;	FOR' COMMAND ROUTINE
LOOK-PROG:	equ $1D86	;	LOOK-PROG' SUBROUTINE
NEXT' COMMAND ROUTINE	:	equ $1DAB	;	NEXT' COMMAND ROUTINE
NEXT-LOOP:	equ $1DDA	;	NEXT-LOOP' SUBROUTINE
READ' COMMAND ROUTINE	:	equ $1DEC	;	READ' COMMAND ROUTINE
DATA' COMMAND ROUTINE	:	equ $1E27	;	DATA' COMMAND ROUTINE
PASS-BY:	equ $1E39	;	PASS-BY' SUBROUTINE
RESTORE' COMMAND ROUTINE	:	equ $1E42	;	RESTORE' COMMAND ROUTINE
RANDOMIZE' COMMAND ROUTINE	:	equ $1E4F	;	RANDOMIZE' COMMAND ROUTINE
CONTINUE' COMMAND ROUTINE	:	equ $1E5F	;	CONTINUE' COMMAND ROUTINE
GO TO' COMMAND ROUTINE	:	equ $1E67	;	GO TO' COMMAND ROUTINE
OUT' COMMAND ROUTINE	:	equ $1E7A	;	OUT' COMMAND ROUTINE
POKE' COMMAND ROUTINE	:	equ $1E80	;	POKE' COMMAND ROUTINE
TWO-PARAM:	equ $1E85	;	TWO-PARAM' SUBROUTINE
FIND INTEGERS:	equ $1E94	;	FIND INTEGERS' SUBROUTINE
RUN' COMMAND ROUTINE	:	equ $1EA1	;	RUN' COMMAND ROUTINE
CLEAR' COMMAND ROUTINE	:	equ $1EAC	;	CLEAR' COMMAND ROUTINE
GO SUB' COMMAND ROUTINE	:	equ $1EED	;	GO SUB' COMMAND ROUTINE
TEST-ROOM:	equ $1F05	;	TEST-ROOM' SUBROUTINE
RETURN' COMMAND ROUTINE	:	equ $1F23	;	RETURN' COMMAND ROUTINE
PAUSE' COMMAND ROUTINE	:	equ $1F3A	;	PAUSE' COMMAND ROUTINE
BREAK-KEY:	equ $1F54	;	BREAK-KEY' SUBROUTINE
DEF FN' COMMAND ROUTINE	:	equ $1F60	;	DEF FN' COMMAND ROUTINE
UNSTACK-Z:	equ $1FC3	;	UNSTACK-Z' SUBROUTINE
LPRINT and PRINT' COMMAND ROUTINES	:	equ $1FC9	;	LPRINT and PRINT' COMMAND ROUTINES
PRINT CONTROLLING:	equ $1FDF	;	PRINT CONTROLLING' SUBROUTINE
PRINT A CARRIAGE RETURN:	equ $1FF5	;	PRINT A CARRIAGE RETURN' SUBROUTINE
PRINT ITEMS:	equ $1FFC	;	PRINT ITEMS' SUBROUTINE
END OF PRINTING:	equ $2045	;	END OF PRINTING' SUBROUTINE
PRINT POSITION:	equ $204E	;	PRINT POSITION' SUBROUTINE
ALTER STREAM:	equ $2070	;	ALTER STREAM' SUBROUTINE
INPUT' COMMAND ROUTINE	:	equ $2089	;	INPUT' COMMAND ROUTINE
IN-ASSIGN:	equ $21B9	;	IN-ASSIGN' SUBROUTINE
IN-CHAN-K:	equ $21D6	;	IN-CHAN-K' SUBROUTINE
COLOUR ITEM' ROUTINES	:	equ $21E1	;	COLOUR ITEM' ROUTINES
BORDER' COMMAND ROUTINE	:	equ $2294	;	BORDER' COMMAND ROUTINE
PIXEL ADDRESS:	equ $22AA	;	PIXEL ADDRESS' SUBROUTINE
POINT:	equ $22CB	;	POINT' SUBROUTINE
PLOT' COMMAND ROUTINE	:	equ $22DC	;	PLOT' COMMAND ROUTINE
STK-TO-BC:	equ $2307	;	STK-TO-BC' SUBROUTINE
STK-TO-A:	equ $2314	;	STK-TO-A' SUBROUTINE
CIRCLE' COMMAND ROUTINE	:	equ $2320	;	CIRCLE' COMMAND ROUTINE
DRAW' COMMAND ROUTINE	:	equ $2382	;	DRAW' COMMAND ROUTINE
INITIAL PARAMETERS:	equ $247D	;	INITIAL PARAMETERS' SUBROUTINE
LINE-DRAWING:	equ $24B7	;	LINE-DRAWING' SUBROUTINE
SCANNING:	equ $24FB	;	SCANNING' SUBROUTINE
SCANNING QUOTES:	equ $250F	;	SCANNING QUOTES' SUBROUTINE
SCANNING TWO CO-ORDINATES:	equ $2522	;	SCANNING TWO CO-ORDINATES' SUBROUTINE
SYNTAX-Z:	equ $2530	;	SYNTAX-Z' SUBROUTINE
SCANNING SCREEN$:	equ $2535	;	SCANNING SCREEN$' SUBROUTINE
SCANNING ATTRIBUTES:	equ $2580	;	SCANNING ATTRIBUTES' SUBROUTINE
SCANNING UNARY PLUS:	equ $25AF	;	SCANNING UNARY PLUS' ROUTINE
SCANNING QUOTE:	equ $25B3	;	SCANNING QUOTE' ROUTINE
SCANNING BRACKET:	equ $25E8	;	SCANNING BRACKET' ROUTINE
SCANNING FN:	equ $25F5	;	SCANNING FN' ROUTINE
SCANNING RND:	equ $25F8	;	SCANNING RND' ROUTINE
SCANNING PI:	equ $2627	;	SCANNING PI' ROUTINE
THE' SCANNING INKEY$:	equ $2634	;	THE' SCANNING INKEY$' ROUTINE
SCANNING SCREEN$:	equ $2668	;	SCANNING SCREEN$' ROUTINE
SCANNING ATTR:	equ $2672	;	SCANNING ATTR' ROUTINE
SCANNING POINT:	equ $267B	;	SCANNING POINT' ROUTINE
SCANNING ALPHANUMERIC:	equ $2684	;	SCANNING ALPHANUMERIC' ROUTINE
SCANNING DECIMAL:	equ $268D	;	SCANNING DECIMAL' ROUTINE
SCANNING VARIABLE:	equ $26C9	;	SCANNING VARIABLE' ROUTINE
SCANNING FUNCTION:	equ $27BD	;	SCANNING FUNCTION' SUBROUTINE
FUNCTION SKIPOVER:	equ $28AB	;	FUNCTION SKIPOVER' SUBROUTINE
LOOK-VARS:	equ $28B2	;	LOOK-VARS' SUBROUTINE
STACK FUNCTION ARGUMENT:	equ $2951	;	STACK FUNCTION ARGUMENT' SUBROUTINE
STK-VAR:	equ $2996	;	STK-VAR' SUBROUTINE
SLICING:	equ $2A52	;	SLICING' SUBROUTINE
STK-STORE:	equ $2AB1	;	STK-STORE' SUBROUTINE
INT-EXP:	equ $2ACC	;	INT-EXP' SUBROUTINE
DE,(DE+1):	equ $2AEE	;	DE,(DE+1)' SUBROUTINE
GET-HL*DE:	equ $2AF4	;	GET-HL*DE' SUBROUTINE
LET' COMMAND ROUTINE	:	equ $2AFF	;	LET' COMMAND ROUTINE
STK-FETCH:	equ $2BF1	;	STK-FETCH' SUBROUTINE
DIM' COMMAND ROUTINE	:	equ $2C02	;	DIM' COMMAND ROUTINE
ALPHANUM:	equ $2C88	;	ALPHANUM' SUBROUTINE
ALPHA:	equ $2C8D	;	ALPHA' SUBROUTINE
DECIMAL TO FLOATING POINT:	equ $2C9B	;	DECIMAL TO FLOATING POINT' SUBROUTINE
NUMERIC:	equ $2D1B	;	NUMERIC' SUBROUTINE
STK-DIGIT:	equ $2D22	;	STK-DIGIT' SUBROUTINE
STACK-A:	equ $2D28	;	STACK-A' SUBROUTINE
STACK-BC:	equ $2D2B	;	STACK-BC' SUBROUTINE
INTEGER TO FLOATING-POINT:	equ $2D3B	;	INTEGER TO FLOATING-POINT' SUBROUTINE
E-FORMAT TO FLOATING-POINT' SUBROUTINE (offset +3C)	:	equ $2D4F	;	E-FORMAT TO FLOATING-POINT' SUBROUTINE (offset +3C)
INT-FETCH:	equ $2D7F	;	INT-FETCH' SUBROUTINE
INT-STORE:	equ $2D8E	;	INT-STORE' SUBROUTINE
FLOATING-POINT TO BC:	equ $2DA2	;	FLOATING-POINT TO BC' SUBROUTINE
LOG(2↑A):	equ $2DC1	;	LOG(2↑A)' SUBROUTINE
FLOATING-POINT TO A:	equ $2DD5	;	FLOATING-POINT TO A' SUBROUTINE
PRINT A FLOATING-POINT NUMBER:	equ $2DE3	;	PRINT A FLOATING-POINT NUMBER' SUBROUTINE
CA=10*A+C:	equ $2F8B	;	CA=10*A+C' SUBROUTINE
PREPARE TO ADD:	equ $2F9B	;	PREPARE TO ADD' SUBROUTINE
FETCH TWO NUMBERS:	equ $2FBA	;	FETCH TWO NUMBERS' SUBROUTINE
SHIFT ADDEND:	equ $2FDD	;	SHIFT ADDEND' SUBROUTINE
ADD-BACK:	equ $3004	;	ADD-BACK' SUBROUTINE
SUBTRACTION' OPERATION (offset +03)	:	equ $300F	;	SUBTRACTION' OPERATION (offset +03)
ADDITION' OPERATION (offset +0F)	:	equ $3014	;	ADDITION' OPERATION (offset +0F)
HL=HL*DE:	equ $30A9	;	HL=HL*DE' SUBROUTINE
PREPARE TO MULTIPLY OR DIVIDE:	equ $30C0	;	PREPARE TO MULTIPLY OR DIVIDE' SUBROUTINE
MULTIPLICATION' OPERATION (offset +04)	:	equ $30CA	;	MULTIPLICATION' OPERATION (offset +04)
DIVISION' OPERATION (offset +05)	:	equ $31AF	;	DIVISION' OPERATION (offset +05)
INTEGER TRUNCATION TOWARDS ZERO' SUBROUTINE (offset +3A)	:	equ $3214	;	INTEGER TRUNCATION TOWARDS ZERO' SUBROUTINE (offset +3A)
RE-STACK TWO:	equ $3293	;	RE-STACK TWO' SUBROUTINE
RE-STACK' SUBROUTINE (offset +3D)	:	equ $3297	;	RE-STACK' SUBROUTINE (offset +3D)
CALCULATE:	equ $335B	;	CALCULATE' SUBROUTINE
SINGLE OPERATION' SUBROUTINE (offset +3B)	:	equ $33A2	;	SINGLE OPERATION' SUBROUTINE (offset +3B)
TEST 5-SPACES:	equ $33A9	;	TEST 5-SPACES' SUBROUTINE
STACK NUMBER:	equ $33B4	;	STACK NUMBER' SUBROUTINE
MOVE A FLOATING-POINT NUMBER' SUBROUTINE (offset +31)	:	equ $33C0	;	MOVE A FLOATING-POINT NUMBER' SUBROUTINE (offset +31)
STACK LITERALS' SUBROUTINE (offset +34)	:	equ $33C6	;	STACK LITERALS' SUBROUTINE (offset +34)
SKIP CONSTANTS:	equ $33F7	;	SKIP CONSTANTS' SUBROUTINE
MEMORY LOCATION:	equ $3406	;	MEMORY LOCATION' SUBROUTINE
GET FROM MEMORY AREA' SUBROUTINE (offset +41)	:	equ $340F	;	GET FROM MEMORY AREA' SUBROUTINE (offset +41)
STACK A CONSTANT' SUBROUTINE (offset +3F)	:	equ $341B	;	STACK A CONSTANT' SUBROUTINE (offset +3F)
STORE IN MEMORY AREA' SUBROUTINE (offset +40)	:	equ $342D	;	STORE IN MEMORY AREA' SUBROUTINE (offset +40)
EXCHANGE' SUBROUTINE (offset +01)	:	equ $343C	;	EXCHANGE' SUBROUTINE (offset +01)
SERIES GENERATOR' SUBROUTINE (offset +3E)	:	equ $3449	;	SERIES GENERATOR' SUBROUTINE (offset +3E)
ABSOLUTE MAGNITUDE' FUNCTION (offset +2A)	:	equ $346A	;	ABSOLUTE MAGNITUDE' FUNCTION (offset +2A)
UNARY MINUS' OPERATION (offset +1B)	:	equ $346E	;	UNARY MINUS' OPERATION (offset +1B)
SIGNUM' FUNCTION (offset +29)	:	equ $3492	;	SIGNUM' FUNCTION (offset +29)
IN' FUNCTION (offset +2C)	:	equ $34A5	;	IN' FUNCTION (offset +2C)
PEEK' FUNCTION (offset +2B)	:	equ $34AC	;	PEEK' FUNCTION (offset +2B)
USR' FUNCTION (offset +2D)	:	equ $34B3	;	USR' FUNCTION (offset +2D)
USR STRING' FUNCTION (offset +19)	:	equ $34BC	;	USR STRING' FUNCTION (offset +19)
TEST-ZERO:	equ $34E9	;	TEST-ZERO' SUBROUTINE
GREATER THAN ZERO' OPERATION (offset +37)	:	equ $34F9	;	GREATER THAN ZERO' OPERATION (offset +37)
NOT' FUNCTION (offset +30)	:	equ $3501	;	NOT' FUNCTION (offset +30)
LESS THAN ZERO' OPERATION (offset +36)	:	equ $3506	;	LESS THAN ZERO' OPERATION (offset +36)
ZERO OR ONE:	equ $350B	;	ZERO OR ONE' SUBROUTINE
OR' OPERATION (offset +07)	:	equ $351B	;	OR' OPERATION (offset +07)
NUMBER AND NUMBER' OPERATION (offset +08)	:	equ $3524	;	NUMBER AND NUMBER' OPERATION (offset +08)
STRING AND NUMBER' OPERATION (offset +10)	:	equ $352D	;	STRING AND NUMBER' OPERATION (offset +10)
COMPARISON' OPERATIONS (offsets +09 to +0E, +11 to +16)	:	equ $353B	;	COMPARISON' OPERATIONS (offsets +09 to +0E, +11 to +16)
STRING CONCATENATION' OPERATION (offset +17)	:	equ $359C	;	STRING CONCATENATION' OPERATION (offset +17)
STK-PNTRS:	equ $35BF	;	STK-PNTRS' SUBROUTINE
CHR$' FUNCTION (offset +2F)	:	equ $35C9	;	CHR$' FUNCTION (offset +2F)
VAL' AND 'VAL$' FUNCTIONS (offsets +18, +1D)	:	equ $35DE	;	VAL' AND 'VAL$' FUNCTIONS (offsets +18, +1D)
STR$' FUNCTION (offset +2E)	:	equ $361F	;	STR$' FUNCTION (offset +2E)
READ-IN' SUBROUTINE (offset +1A)	:	equ $3645	;	READ-IN' SUBROUTINE (offset +1A)
CODE' FUNCTION (offset +1C)	:	equ $3669	;	CODE' FUNCTION (offset +1C)
LEN' FUNCTION (offset +1E)	:	equ $3674	;	LEN' FUNCTION (offset +1E)
DECREASE THE COUNTER' SUBROUTINE (offset +35)	:	equ $367A	;	DECREASE THE COUNTER' SUBROUTINE (offset +35)
JUMP' SUBROUTINE (offset +33)	:	equ $3686	;	JUMP' SUBROUTINE (offset +33)
JUMP ON TRUE' SUBROUTINE (offset +00)	:	equ $368F	;	JUMP ON TRUE' SUBROUTINE (offset +00)
END-CALC' SUBROUTINE (offset +38)	:	equ $369B	;	END-CALC' SUBROUTINE (offset +38)
MODULUS' SUBROUTINE (offset +32)	:	equ $36A0	;	MODULUS' SUBROUTINE (offset +32)
INT' FUNCTION (offset +27)	:	equ $36AF	;	INT' FUNCTION (offset +27)
EXPONENTIAL' FUNCTION (offset +26)	:	equ $36C4	;	EXPONENTIAL' FUNCTION (offset +26)
NATURAL LOGARITHM' FUNCTION (offset +25)	:	equ $3713	;	NATURAL LOGARITHM' FUNCTION (offset +25)
REDUCE ARGUMENT' SUBROUTINE (offset +39)	:	equ $3783	;	REDUCE ARGUMENT' SUBROUTINE (offset +39)
COSINE' FUNCTION (offset +20)	:	equ $37AA	;	COSINE' FUNCTION (offset +20)
SINE' FUNCTION (offset +1F)	:	equ $37B5	;	SINE' FUNCTION (offset +1F)
TAN' FUNCTION (offset +21)	:	equ $37DA	;	TAN' FUNCTION (offset +21)
ARCTAN' FUNCTION (offset +24)	:	equ $37E2	;	ARCTAN' FUNCTION (offset +24)
ARCSIN' FUNCTION (offset +22)	:	equ $3833	;	ARCSIN' FUNCTION (offset +22)
ARCCOS' FUNCTION (offset +23)	:	equ $3843	;	ARCCOS' FUNCTION (offset +23)
SQUARE ROOT' FUNCTION (offset +28)	:	equ $384A	;	SQUARE ROOT' FUNCTION (offset +28)
EXPONENTIATION' OPERATION (offset +06)	:	equ $3851	;	EXPONENTIATION' OPERATION (offset +06)

